### ISSUE TITLE
Rating / Export

### ISSUE THREAD

**Issue by dnkzn** [Glagan/MyMangaDex#11]
Less of an issue but more of a question: Is there a way to pass the rating of each individual manga over to MAL? If not this would be something I'd love to see in the future!

Also 'Export MAL' doesn't properly update the chapters when used. This is not much of a problem for ongoing usage but if you start using this plugin midway in like me (and always have tons of manga on the MangaDex list) it kinda is.

Edit: An option to prevent manga from being added to MAL when your'e not following it or it's just set to 'plan to read' would be nice. I usually skip through some random chapters while deciding if it's worth starting to read the manga in the first place. At this point the plugin will just add it to MAL no matter what.

Just figured you'd want some feedback too. 
Anyways - thanks for making such an awesome plugin. I really appreciate it!

**Comment by Glagan** [comment]
Passing the rating to MyAnimeList could be easy to do, I will look into it.

I think I understand your problem with the Export MAL feature, it's because it's more for first time users, I guess, because it use MyMangaDex information, so any chapter you didn't open *after* installing the extension can't be updated on MyAnimeList.
Something to initialize all chapters to what you actually read on MangaDex could be made tho.

**Comment by dnkzn** [comment]
I was thinking about the plugin considering your status on the manga. I'm talking about that 'reading', 'completed' 'plan to read' stuff. So that when no status is set it just doesn't add it (as Mangadex does the same internally). I figured you already worked in that direction since it's actually correctly passing it over to MAL.

Don't feel pressured by me btw. I just know it's nice sometimes to get some feedback. Especially when you put quite alot of work into something.

You also you got a pretty fast tech support on hold here haha.

**Comment by Glagan** [comment]
Well, I'm *working* but available :)

I understand, I could be looking at the MangaDex status and if it's not in a list, not update it in MyAnimeList, this conflict a bit with the `Update MangaDex status` option but I can still make it work.
And i'm not currently reading the MangaDex status to update MyAnimeList, i'm doing the opposite, I guess the status based on the chapter and if it's the last one I set it to completed, else I set it to reading.

Personally i'm doing the opposite, I never touch the reading status on MangaDex and I let the extension update it.
I'll think about how I can do what you ask, I don't even know if I can get the MangaDex status for the manga whem you're reading a chapter.

**Comment by dnkzn** [comment]
I got used to changing it manually. Especially because of that random clicking through manga/chapters that I do to find new stuff I'm interested in. I think I'm somewhat special in that area.

And yes, I get what you mean. Some option like that would turn the 'Update MangaDex status' obsolete. You could maybe add an easy accessible 'kill switch' somewhere on the Mangadex site that completely prevents the plugin from adding/changing while turned on. Maybe even make an option for it to be shown or not.

Sadly I'm not that experienced when it comes to JS. Only wrote some simple stuff to this point. Else I'd give you a hand and provide some code or more technical input...

**Comment by Glagan** [comment]
@dnkzn Sorry to respond this late, I was busy in June and recently started working on MyMangaDex.
Anyway, I made everything and added an option to update only if the title is in your MangaDex list, and also a confirm button if you still want to add it :)

I will maybe push it tomorrow, I need to do some more tests and also add a way to send the MangaDex rating (but it should be easy enough).

**Comment by dnkzn** [comment]
Thanks alot! :)
