### ISSUE TITLE
Starting old series, hide newer chapters than last read option?

### ISSUE THREAD

**Issue by germzx** [Glagan/MyMangaDex#14]
Upon starting an older series with 100+ chapters and being on chapter 15, I was trying to find an option for hiding chapters beyond the next to read. For caught up series it could show the last read chapter which could disappear and only show the next to read chapter when it releases, and for old series it could only show the next to read. 

This would make the "following" page much less cluttered when staying up to date on multiple series while reading a few older series. 

Is this or something similar possible? I went from having 1 page on my following area to having 3 just from adding one old series that has 100+ chapters released.

**Comment by Glagan** [comment]
I see the problem, it shouldn't be hard to hide the chapters above your next chapter to read, but I can already tell you that if you don't follow a lot of titles you will end up with empty pages and you will have to find the page that have the next chapter you need to read.
I will try to make it tomorrow.

**Comment by Glagan** [comment]
Sorry it took so long.
I added an option to hide higher chapters, and I also added another option ``Higher chapters color`` to highlight higher chapters if you want (if they are not hidden, or when you show them using the button).
It is ``transparent`` by default so it won't highlight anything.

I will probably do more tests and publish the update tomorrow.
