### ISSUE TITLE
Change thumbnails size on chapter list

### ISSUE THREAD

**Issue by Jerrk** [Glagan/MyMangaDex#15]
i really like the "show tooltips (thumbnails)" option but the thumbnail is a little too small for my taste, is there a possibility to give us an option to change its size? 

thanks

**Comment by Glagan** [comment]
I am using the only thumbnail MangaDex offer, the next bigger picture is the full cover which is generally big, so it could use a lot of data since hovering a row can be fast, but I will add an option to display the full original image.

**Comment by Glagan** [comment]
The extension of the file isn't always the same for the cover, but I found an ugly way to still display it (I hope it doesn't do too much useless requests to MangaDex).
It looks like this:
![2019-09-11_02-24-50](https://user-images.githubusercontent.com/8447621/64659344-90434f00-d43b-11e9-84d9-6833b7447b48.gif)
I also updated the tooltip code to display a spinner while it's loading and there shouldn't be anymore weird position bugs after loading.

I also added another option, ``Next chapter color`` which you can see in the GIF,  because as I thought it *is* hard to find the next chapter of a title.

I will probably do more tests and publish the update tomorrow.

**Comment by Jerrk** [comment]
I seem to have a problem where if i hover over anything other than the manga title, the thumbnail will sometimes cover my whole screen

hovering chapter title
https://i.imgur.com/jTQPQFL.jpg

-refreshing page-

hovering manga title
https://i.imgur.com/KAPVgSC.png

This seems to be a problem if there is no margin to the left of the page, i use a portrait monitor and i believe that is my issue here, is that something that can be fixed in the script or should i try to figure out some css to take care of it?

If i run my cursor over a bunch of chapter titles in quick succession it it pretty easy to replicate
https://streamable.com/lqv72

**Comment by Glagan** [comment]
What browser are you using ?

I think I can see where this error come from, I will try to replicate on my own and I'm sure I can fix it, don't worry about making your own CSS ;)

**Comment by Jerrk** [comment]
i'm on firefox nightly ver. 71.0a1

**Comment by Glagan** [comment]
I think I fixed one problem for now, the fact that you are using portrait mode might cause a bug if you have a very large screen (I am using the width of the screen to set the max width), but I should have fixed it too.
Some tooltips still get *stuck* for some reasons after you stop hovering a row, I will try to fix that and I will publish an update.

**Comment by Glagan** [comment]
I published an update that should be already up for Firefox and soon for Chrome.
I'll let this issue open until you tell me everything is working fine.

**Comment by Jerrk** [comment]
https://i.imgur.com/HKagTB2.gifv

They no longer fill up my screen but they're back to the old size which i thought was too small as you can see when i hover the manga title the size is perfect but when i hover the chapter title it is about half the size

**Comment by Glagan** [comment]
What is your screen resolution ?
If there is less available space on the left the thumbnail **will** be smaller.
I also set a reasonable width based on the available space to avoid the tooltip to be really tall and being croped to fit on the screen.

**Comment by Jerrk** [comment]
1440x2560
so yeah it is wider than normal
https://i.imgur.com/DzEForB.png
the thumbnail could be about 150 more pixels wide to fit for me
is it possible to setup the tooltip to fill the manga title column perhaps? or does it have to be a fixed pixel width?
https://i.imgur.com/3rMIGIl.png

**Comment by Glagan** [comment]
How big would be an acceptable width ? I can make it to use the maximum amount of available width and scale it so the tooltip doesn't crop the cover, but isn't it a bit too big ? Should I make it a bit lower ?

![image](https://user-images.githubusercontent.com/8447621/65328870-9b267e00-dbb7-11e9-9e68-c0962a5a53fb.png)

**Comment by Jerrk** [comment]
For me (1440x2560 monitor, portrait mode, preference, etc.)I believe a max-width of 400 would be ideal and a min-width of let's say 320. I'm not sure you should cater specifically to my use-case though 😄. 

Maybe give us an option in the settings to input our preferred width/height? or give us a couple options i.e 80% height OR original size OR max width of 100px, etc.

**Comment by Glagan** [comment]
I added a ``maxCoverHeight`` option that set the maximum percentage of your screen a tooltip can take.
It is 80% by default so they aren't *too* big, but you can set it from 1 to 100%.

I published the update and it's up for Firefox. Tell me if everything's working !

**Comment by Jerrk** [comment]
That works great now, i set it to 25% which is just perfect for me 😄
