### ISSUE TITLE
Export (MAL) option unable to find/update MAL entries

### ISSUE THREAD

**Issue by awwang** [Glagan/MyMangaDex#16]
When attempting to export MD follows to MAL, the titles are all scanned correctly. However, when attempting to update them on MAL, I get the error, "No MyAnimeList id, skip" for every single title. 

I'm not sure if I am doing something incorrectly. Titles update successfully when I update manually on the MangaDex modal or when I read a chapter.

**Comment by Glagan** [comment]
MangaDex recently updated it's link to services like MyAnimeList, Anilist and others, it might have broke the way I find the link I will look at it.

**Comment by Glagan** [comment]
They changed the path to the thumbnails that I was using, I fixed it and it should be up for both Firefox and Chrome.
