### ISSUE TITLE
Doesn't recognize the new .cc domain currently being used for mangadex

### ISSUE THREAD

**Issue by Bananaramahamadama-sama** [Glagan/MyMangaDex#17]

**Comment by Glagan** [comment]
I will make a quick patch.

**Comment by Glagan** [comment]
Fixed with commit [98dd9e54dd13b954649c08ccc81e88e278729aa7](https://github.com/Glagan/MyMangaDex/commit/98dd9e54dd13b954649c08ccc81e88e278729aa7).

Tell me if there is something not working :)
