### ISSUE TITLE
Opening chapter on new manga shows error when added

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#18]
When I open a chapter from my follows page, I get either the error message that the manga was not found on MyAnimeList (as expected) or I get that message *and* the one saying it was added to my list. It wasn't found but could be added?
![Messages](https://user-images.githubusercontent.com/59023762/71784898-3291ce80-2ff9-11ea-849d-9b13497f2e6a.png)

**Comment by Glagan** [comment]
If you open a **/title** page it says manga not found on **MyAnimeList** but if you open an actual chapter it show the two notifications in the screenshot ? Or do you have two notifications saying manga not found on **MyAnimeList** **and** a notification saying manga started ?

Can I have a link to a manga that have this issue, Gokushufudou is working for me on both Firefox and Chrome.
Also, which browser are you using ?

**Comment by cpiber** [comment]
I believe this only happens when opening a chapter without first visiting the title page (for example directly from follows).
The screenshot is when I opened the chapter from follows (wasn't on list), these two notifications were displayed at the same time.
Try clicking this link, should show both notifications: https://mangadex.cc/chapter/778869
Using FireFox.

**Comment by Glagan** [comment]
Ho, I see what you mean. Yes if you never visited a **/title** page it doesn't have a possible **MyAnimeList** ID and will search it, that's what it's doing.
The notification title is misleading, it doesn't mean MyMangaDex didn't find a MAL ID, but that there wasn't one initially, I will change it up, thanks :)
