### ISSUE TITLE
Ch.0 Not beeng tracked/hidden.

### ISSUE THREAD

**Issue by Tigoreetur** [Glagan/MyMangaDex#20]
On the "Follows" page, manga "Ch.0" and "Oneshot" aren't being hidden with the "Hide lower chapters" option.
![pic-selected-200118-1507-24](https://user-images.githubusercontent.com/31919120/72664263-9eaa0480-39f3-11ea-9553-2d3fb96334ae.png)

**Comment by Glagan** [comment]
Hum, yes, actually I opened Chapter 0 and it updated to Chapter 1, I will look at it.

**Comment by Glagan** [comment]
It *should* be fixed with the last release, you can close this issue if it *really* is.
