### ISSUE TITLE
[Request] Dates of last accessed to the History

### ISSUE THREAD

**Issue by Doomwhite** [Glagan/MyMangaDex#22]
It would be something like this:
In the /history page you could hover any manga and after like 1 second it would should a tooltip and you would know the date that it was last read/accessed by you.

**Comment by Glagan** [comment]
It shouldn't be too hard, is the last time you read a chapter enough, or do you want also the last time you visited the title page ?

**Comment by Doomwhite** [comment]
Could you define what's "read a chapter"? It could be either you just opened the chapter page or it updated MAL. 
"or do you want also the last time you visited the title page ?" 
Well, that would be cool as well :P.

**Comment by Glagan** [comment]
I added it in the last release, it looks like this 
![image](https://user-images.githubusercontent.com/8447621/72724388-76e9a680-3b83-11ea-8047-0f8247ef2c03.png)

The first date is the last chapter you read, by read I mean updated to MyAnimeList if there was a MyAnimeList id (and if you clicked the "Accept" button if enabled), or everytime (I think) if there is none.
The second date is the last time you visited the title page of the title.

I now also check every 3 days if there is a MyAnimeList id while reading if the title don't have one, so no need to go to a title page to have it updated.
