### ISSUE TITLE
Title parsing bug

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#23]
I noticed that in the newest version the Manga title in the popup is wrong. Seems to only be a problem of the update-popup, not the searching-page one.

![image](https://user-images.githubusercontent.com/59023762/73279066-d2074300-41ec-11ea-9a1c-581ec7bfc893.png)
(Should be until the , after "Expelled from the Hero Party~"

**Comment by cpiber** [comment]
Update: Now also saw it on a searching-page-popup, possibly related to comma in title

**Comment by Glagan** [comment]
MangaDex changed the text I was using to find the title, it's fixed, thanks.
