### ISSUE TITLE
[Enhancement] Don't mark delayed chapters as read

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#29]
When a group delays a chapter, it should not be set as the most recently read
![image](https://user-images.githubusercontent.com/59023762/74730350-3ba3cb80-5246-11ea-872c-8c9fd22620f6.png)

**Comment by Glagan** [comment]
Sorry, I made the fix but couldn't test it since MyAnimeList was down at the time I wrote it, and I totally forgot about it, it *should* be fixed.
If there is still an error with delayed chapters you can re-open this issue.

**Comment by cpiber** [comment]
Fixed with PR #35
