### ISSUE TITLE
Export (MAL) gets stuck whenever it encounters a "No MyAnimeList id, skip."

### ISSUE THREAD

**Issue by gimmedeath** [Glagan/MyMangaDex#30]
If there is no mal entry then it shows "No MyAnimeList id, skip." and gets stuck on the message. When I reload the page it will skip that entry but get stuck on the next "No MyAnimeList id, skip.".

**Comment by Glagan** [comment]
Whoops, thanks it should be fixed.
If you're using Chrome I have no idea if it is already available or when it will be, sorry it's on their end.
