### ISSUE TITLE
MAL Api

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#34]
In 2019/2020 a new Api was added to MAL, might be worth looking into:
https://github.com/SuperMarcus/myanimelist-api-specification

Substitute v0.21 with v2 according to https://myanimelist.net/forum/?topicid=1804432

**Comment by Glagan** [comment]
The MAL API is still not public and I don't have access to it, so... I don't know if they ever will release it, it's been a very long time...
But if they ever to, I'll be sure to look at it since it would reduce the code size.
