### ISSUE TITLE
Options not saving

### ISSUE THREAD

**Issue by Glagan** [Glagan/MyMangaDex#4]
This actually happens to me now. On top of that, the options changes are not saved every time.
May I ask what did you do or change at that time to fix this issue?

_Originally posted by @ariobw in https://github.com/Glagan/MyMangaDex/issues/3#issuecomment-460128109_

The extension was updated to version 2 since @wghassen posted this issue, I don't know if his fix would work. Can you tell me more about your problem ?

**Comment by wghassen** [comment]
I cleared the browser's cache , reinstalled the extension and restarted the pc.

**Comment by Glagan** [comment]
Maybe something didn't save right and "corrupted" the save.
Normally, only exporting the save if you want to save it and reset using the delete button and importing the save should fix it, reinstalling the extension and restarting your computer shouldn't affect it, maybe restarting firefox.
Waiting for @ariobw to see if it works, thanks wghassen.

**Comment by Glagan** [comment]
Ok, I found the error and it was actually a third party needed for Chrome, Chrome extension async that needed to be updated.

It should now work, your extension will be updated when chrome accept it, which should take not more than 1hour.

Thanks.

**Comment by ariobw** [comment]
It works perfectly now with the version 2.0.2 extension. Thanks a lot!
