### ISSUE TITLE
MangaDex rating also sets MAL rating

### ISSUE THREAD

**Issue by hoover900** [Glagan/MyMangaDex#44]
It would be cool if when you set a rating a series on MangaDex it mirrors that score to MAL.

**Comment by Glagan** [comment]
The opposite actually works, if you set a score on MyAnimeList it should update the MangaDex score, but the MangaDex score dropdown is more accessible, I will try to add it, it's actually just one request on the MangaDex part.

**Comment by hoover900** [comment]
kk, I'll give setting the MAL rating first a go.

**Comment by Glagan** [comment]
I actually added what you want, in the next version when you click a score in the MangaDex score dropdown it's going to update both MangaDex and MyAnimeList.
I'm just doing other things right now and I'll publish the update when it's possible.

**Comment by hoover900** [comment]
awesome, keep up the good work man
