### ISSUE TITLE
[Bug] 'Plan to Read' does not update to 'Reading'

### ISSUE THREAD

**Issue by hoover900** [Glagan/MyMangaDex#45]
If you start reading a manga marked as **Plan to Read** you get a status update saying it's marked as **Started Reading**, however it does not update the MangaDex status to **Reading**.

**Comment by hoover900** [comment]
It looks like this only happens when the manga is not listed on MAL, otherwise it works as expected.

**Comment by hoover900** [comment]
A manga not listed on MAL for testing
https://mangadex.org/title/47260

**Comment by Glagan** [comment]
Is there a **Status on MangaDex updated** notification, if there isn't the status isn't being updated.  
Make sure you also have the **Update MangaDex list** option enabled.

**Comment by hoover900** [comment]
**Update MangaDex List** is enabled and I'm getting the status update pop up in the lower left. The chapter is list is highlighted as if I read it, but the status is still set to **Plan to Read**

**Comment by Glagan** [comment]
There was a missing condition after an update, it should work now.
