### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by Jerrk** [Glagan/MyMangaDex#46]
Firefox Nightly 79.0a1 (2020-06-14) (64-bit)

Removed all settings, reinstalled the add-on, disabled all other add-ons, disabled VPN, relogged on both MAL and MD, Latest version 2.4.3, works just fine on chrome.

I know there has been an issue with MAL in the past couple of weeks if you were using a VPN, but i have this issue even without the VPN, and i don't even have the issue in chrome WITH VPN, so im assuming something is broken for firefox.

My issue is the status will never appear and no tracking seems to be occurring. 
![](https://i.imgur.com/aeQ9bUA.png)

The firefox console doenst seem to be throwing any obvious errors either.

Hopefully you would know what to look for in troubleshooting this error.

**Comment by cpiber** [comment]
I don't have nightly installed, can you please open Web Developer > Browser Console and reload the page, then see if you can see any errors there?

**Comment by Glagan** [comment]
I can't load MAL at all for weeks now, In both Firefox and Chrome it's just the site itself that banned me, maybe you're justed "banned" too.
There is a thread on their forum following the issue, and a post to send a message https://myanimelist.net/forum/?topicid=1841882&show=200#msg59990347
