### ISSUE TITLE
Bidirection status sync [Feature Request]

### ISSUE THREAD

**Issue by hoover900** [Glagan/MyMangaDex#47]
It would be cool if you changed a status of a manga from the MangaDex drop down menu that it updates both MangaDex & MAL. For example if you set the status to **Plan to Read** it will only set the status in MangaDex, but if you set the MAL status it sets both.

**Comment by Glagan** [comment]
Sorry for the delay, I'll look into that, it shouldn't be hard and just like the rating.  
In the meantime, if you want to quickly add to your **Plan to Read** list you should have a button (if the title can be added on MyAnimeList) and it should set both if you have the correct options enabled.

**Comment by Glagan** [comment]
Sorry for the delay, seems like I totally forgot about this.  
This is available in [SyncDex](https://github.com/Glagan/SyncDex) (still in beta) with the ``MangaDex Buttons update SyncDex`` option enabled.

**Comment by hoover900** [comment]
sweet, I'll check it out. thanks for the epic work man
