### ISSUE TITLE
Online save function, bugged or am I doing it wrong

### ISSUE THREAD

**Issue by germzx** [Glagan/MyMangaDex#48]
I recently got a new laptop and I'm trying to keep my laptop and desktop synced depending on which I am using at the time. I am unclear as to how to properly do this with the online save functionality. 

I am on chrome or edge, go to MMD > Online Save. Enter my credentials, the same for both computers. On my desktop where my data was I then clicked Export. The screen flashed red and showed a bar with no text (On my laptop this momentarily said something like Invalid, or Unavailable, but I couldn't read it in time and it vanished, and subsequent attempts also produced this red box with no text. 

![Untitled](https://user-images.githubusercontent.com/55007032/84980263-36bd2e80-b0f7-11ea-8b68-709e3fd061de.png)

Pressing Import flashes green, but it hasn't uploaded anything and so my list remains empty. And of course Importing on desktop overwrites (so it essentially deletes my data) which I backed up ahead of time.

I see you say you "propose a default (MMD Online Save instance)." Would I be correct that entering log in credentials, logging in, then pressing export should work, or are you saying "set up a URL like this using the MMD Online save program found at that link" and the online URL "https://mmd.nikurasu.org/api/" is just an example.

**Comment by Doomwhite** [comment]
There's also this: 
![image](https://user-images.githubusercontent.com/40442835/84984973-485fff80-b112-11ea-804d-b03a4fcf6059.png)

**Comment by Glagan** [comment]
It's an error on the server part, I'll check the logs.  
If it was working a simple Export online on the computer with your complete save and a Import on the other side should be enough.

**Comment by Glagan** [comment]
@germzx This *should* be fixed, your save might have a bad key somehow.

Can you try again and see if you have any errors ?

**Comment by germzx** [comment]
Perfect! That fixed it and it's working on both devices. Yeah I was aware I could manually export and import via google drive but this is way easier. Thanks for your super fast implementations and support. This add-on rocks.
