### ISSUE TITLE
Not logged in

### ISSUE THREAD

**Issue by Glagan** [Glagan/MyMangaDex#5]
If you keep seing the notification **"Not logged in"** while you *are* actually logged in MyAnimeList, you may need to update some options.

You need to go to [about:config](about:config) and update the option ``network.cookie.cookieBehavior`` to **0** and ``privacy.firstparty.isolate`` to **false**.

The extension need to access cookies from MyAnimeList trough MangaDex to be able to tell you are logged in.

**Comment by Glagan** [comment]
If you are using containers and seeing the notification, you have to make sure to be logged in on MyAnimeList in the **main process**, outside of any container.

**Comment by Korgi2** [comment]
Issue is still persisting for me even after these changes. Also "privacy.firstparty.isolate" seems to be a true/false
