### ISSUE TITLE
Exporting to MAL force abort whenever it cannot find manga.

### ISSUE THREAD

**Issue by awesomecabbage20** [Glagan/MyMangaDex#52]
I have tried to run MyMangaDex on both chrome and firefox when attempting to Export to MAL from MD. 
It would go through all of my manga completely fine but once it hits a manga that it cannot update it forces an abort and I can't get around it.
Here is what it exactly gives me:

> Updating #16224
Error updating the manga. Retrying...
Error updating the manga. Retrying...
There was an error while receiving info from MyAnimeList, aborting.

**Comment by Glagan** [comment]
The first error message means either **MyMangaDex** is sending a bad request or **MyAnimeList** was down at the time of the request.

Can I have your save (you can send it to me on Discord ``Glagan Pas Glagan Pas Lolicon#4411``) to check the MyAnimeList ID associated with the MangaDex ID.  
If you don't want to send me your save you can search the id yourself by searching for ``"16224"`` and checking the following ``"mal"`` value in the JSON.

The found MyAnimeList ID seems fine on MangaDex, maybe MyAnimeList was down for a moment at the time of your request, it happens quite some times now.
