### ISSUE TITLE
"Not Logged In" error persists after fix in Private Browsing

### ISSUE THREAD

**Issue by Korgi2** [Glagan/MyMangaDex#54]
Hello,

After installing this plugin I have had the issue of it not recognizing I am logged in when I am. I tried the fix in advanced options(in firefox) however after toggling both of them the issue still persists. I am currently using the newest version of Firefox. I have tried logging out and back in as well as reinstalling the plugin however it didn't seem to fix the issue. I have also tried disabling Firefox's enhanced tracking feature, ublock origin, privacy badger, and any possible combination of the three as well. 
![image](https://user-images.githubusercontent.com/61196219/89348494-a58c2200-d67a-11ea-94b1-8eacf9e8dcd7.png)
![image](https://user-images.githubusercontent.com/61196219/89348510-b046b700-d67a-11ea-81a7-e72b2ab61133.png)
![image](https://user-images.githubusercontent.com/61196219/89348543-bd63a600-d67a-11ea-9340-6f3692295fa8.png)

**Comment by Korgi2** [comment]
Update: It works in normal Firefox but not private browsing.

**Comment by Glagan** [comment]
Sorry for the late reply, Firefox recently separated extensions in Normal/Private browsing, did you enable MyMangaDex in Private browsing ?
You can check if it's enabled in the **Add-ons** list, click on **MyMangaDex** and look for this checkbox:
![image](https://user-images.githubusercontent.com/8447621/89349195-17ca2a00-d6ae-11ea-81f5-ac3fe2244d1d.png)

**Comment by Korgi2** [comment]
Yeah I enabled it for private browsing when I installed it. For some reason it's having difficulty communicating with MAL though.

**Comment by Glagan** [comment]
Everything's fine for me in Private browsing, but it seems like it picks the MyAnimeList account from *outside* Private browsing, and that's certainly a bug, I'll check that.

In the meantime you can browse MangaDex in Private browsing but you'll need to be logged in on MyAnimeList in normal browsing.  

The same thing also seems to happen with containers, so you can't even use them instead. It should be the same bug, I'll check that too.

**Comment by Korgi2** [comment]
Alright, thanks for the timely reply. Hopefully it's just a minor bug.

**Comment by Korgi2** [comment]
Update: Not really important for the bug but I noticed in my private browsing it won't connect to logged in MAL in main browsing even if I'm logged in both places.

**Comment by Glagan** [comment]
Before a request is sent, the context is checked and cookies from the tab context only are sent, which means you can now be logged on any container, or private browsing and it should only pick the MyAnimeList/MangaDex account of the container, or private browsing.

For you last update, seeing the MyAnimeList account from Private browsing should not be expected anyway, and it now shouldn't work.

Tell me if it still doesn't work, the update should already be up.

If any Chrome user is reading this, Chrome is weird (to be nice) and doesn't work like Firefox.  
I can't do the same things and separate normal/private browsing, it just doesn't work, or I haven't found how to make it work yet, so it's still broken on Chrome and it will probably stay like that.

**Comment by Korgi2** [comment]
It is updating as long as i have logged into MAL on main browsing. Is that what it is supposed to do now? When you say "For you last update, seeing the MyAnimeList account from Private browsing should not be expected anyway, and it now shouldn't work." I'm confused if that means it won't work at all in private.

**Comment by Glagan** [comment]
Now, everything is in it's own *container*.  
If you want to update in private browsing, you should be logged in in private browsing, and it should not pickup any other account you're logged in from (not any container, nor normal browsing).

What shouldn't work now (and should never have) is updating from private browsing, without being logged in in private browsing, while being logged in in normal browsing.

With your last comment, if I understand correctly, you updated from private browsing, while being logged out in private browsing and logged in in normal browsing ?

**Comment by Korgi2** [comment]
Yeah and that's whats working for me. I might need to redownload the plugin to update it I suppose.

**Comment by Glagan** [comment]
In the Options, or in the same page where you can see if the extension is allowed in private browsing, you can see the version, it should be 2.4.8.

**Comment by Korgi2** [comment]
It seems I'm still on 2.4.7 let me update it.
