### ISSUE TITLE
There was an error while receiving info from MyAnimeList, aborting.

### ISSUE THREAD

**Issue by FantasySokka** [Glagan/MyMangaDex#55]
Hey, when I to run MyMangaDex on chrome to export to MAL from MD, it goes smooth until I get this error. It just sits like that does't move and I don't know how to fix it, after I saw I got the error I went to MAL and saw that the site was saying to much activity and I needed to click something to get ti back to normal. Would appreciate any help. Thank you.

Updating #1413
Error updating the manga. Retrying in 1.5s...
Error updating the manga. Retrying in 3s...
There was an error while receiving info from MyAnimeList, aborting.

**Comment by Glagan** [comment]
MyAnimeList recently added this *captcha*... were you using MyAnimeList/MyMangaDex while it was exporting ?  
I increased the time between requests and when I tested it it worked fine, maybe they made it even more strict and I'll just increase the time again.

**Comment by FantasySokka** [comment]
I had the sites open but wasn't using them.

**Comment by FantasySokka** [comment]
Tried it a few times still getting the error but with different numbers, waited for about 1h at least on one of the tries so I don't think time will fix it.

**Comment by Glagan** [comment]
No the problem is just the time between the requests, and also the fact that I think MyAnimeList handle a redirection as 2 requests, and when a Title is not in your list, it does a redirection.  
I'll add more time and check for redirections.

**Comment by FantasySokka** [comment]
Thank you.

**Comment by Glagan** [comment]
Sorry for the delay, I believe I just missed a sleep before requests actually...  
But I increased the time between requests a little bit and added a check before exporting to avoid redirects, I didn't see the captcha in 200 requests it should be fine now.

I don't know when it will be up on Chrome, might be long since it's sunday.
