### ISSUE TITLE
[Bug] Changing information in the modal on title page duplicates languange selector

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#56]
As title says, saving the modal creates a new language selector instead of reusing old one. Similar code should be there for hiding read chapters for consistency.
![image](https://user-images.githubusercontent.com/59023762/91889644-70c9b580-ec8e-11ea-8757-96b9311fbaf2.png)

**Comment by Glagan** [comment]
Didn't think about that, It's fixed.

What do you mean by ``Similar code should be there for hiding read chapters for consistency.`` ?  
There is no hidden chapters in **Title Page**, and hidden chapters in **Chapters List** should remain hidden/visible according to the other options (hide lower, hide higher etc...)

**Comment by cpiber** [comment]
It's not on the title page but on follows page. I solved that issue there previously when I was implementing the recoloring/updating. These add a button to toggle "Show hidden"/"Hide hidden".

**Comment by cpiber** [comment]
Now that I think about it, having a title update on the follows page (7 can be updated from MAL) could also break this on follows

**Comment by Glagan** [comment]
I'm not sure what's happening, the **Show Hidden** button is still here.
![image](https://user-images.githubusercontent.com/8447621/91890666-1fbac100-ec90-11ea-92c6-14515fb25626.png)

It's just hidden if there is nothing hidden.

Ho, I think I get it, having the option to update MAL from the Follow List would break something ? I'm not sure, I didn't touch anything related to that (except the Thumbnail code which was broken) and the new code add unrelated CSS classes to be able to hide/show without looking at the other options.

**Comment by cpiber** [comment]
What I meant that the logic of replacing/updating is already done with this button (might be good to make them similar for consistency in the code base)

The problem I fear might appear this: On the follows page, first the logic to color, hide etc is run once, then, if enabled, the first 7 manga are updated from MAL, then the same logic is called. If these language selectors are created in that same process, the update might also create a second one. Haven't tested it though.

**Comment by Glagan** [comment]
I get it, didn't remember that ``chapterListPage`` was calling itself after updating MyAnimeList.

It's fixed too.

**Comment by Glagan** [comment]
Should be good, I just check if I already added the button, nothing else to check since the chapters never change on the page.  
I also fixed an error that displayed hidden chapters in all languages with the "Show Hidden" button.

**Comment by cpiber** [comment]
I can't reopen this issue but I think it belongs here: In 'chapter list' when updating (recoloring), the selected language is ignored, even with a default set. Quick way to test: Click on read/unread eye.

Example title: https://mangadex.org/title/50728/the-demon-king-s-daughter-is-way-too-easy has chapters in English and Chin. Simp.

**Comment by Glagan** [comment]
Hum, it's the same code... it shouldn't open hidden chapters if it doesn't even create new buttons, I'll look at that.

**Comment by Glagan** [comment]
I was actually applying the CSS classes multiple times, which actually show all rows by default. It's fixed.
