### ISSUE TITLE
Extended History

### ISSUE THREAD

**Issue by vessalioz** [Glagan/MyMangaDex#57]
I have noticed that the extended history setting does not work completely. While adding additional titles to the history page works out fine, beyond the 10 titles originally there, the titles 11+ are all the same title regardless of what I have read. As seen below, I opened a chapter to progress the history page, yet the entry "Reincarnated Vol 1 Ch 10" disappears into the entry "Toorigakari" which has not moved.
![Screen Shot 2020-09-03 at 4 34 22 PM](https://user-images.githubusercontent.com/70729260/92183559-a47a1c00-ee03-11ea-980d-fbb1c4b501ed.png)
![Screen Shot 2020-09-03 at 4 35 21 PM](https://user-images.githubusercontent.com/70729260/92183572-aba12a00-ee03-11ea-9db5-361e106ca850.png)

**Comment by Glagan** [comment]
I see you manually set a limit to 70, is the title somewhere below or it just totally disappeared ?  
It might be the way I prune the history list.

**Comment by Glagan** [comment]
There was a typo in the variable name... I wonder how it was working up until now.. Thanks.
