### ISSUE TITLE
Export Online Error 500

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#59]
Saving to online returns error 500 (also only a blank error is actually displayed, I needed to open the browser console).

![image](https://user-images.githubusercontent.com/59023762/94831244-ca97d980-040c-11eb-8878-7ccdb85df922.png)

Updating individual titles works.

**Comment by Glagan** [comment]
I believe it was a stupid problem with the scope of a variable in the backend, should be fixed.  
I'll look to add a notification, but I won't publish an update for it since there isn't a lot of people using it, and it *shouldn't* happen again.

**Comment by cpiber** [comment]
Yes, works now, thanks
