### ISSUE TITLE
Import from MAL does not work

### ISSUE THREAD

**Issue by ringosham** [Glagan/MyMangaDex#6]
It's able to grab the list from MAL, but cannot import to MangaDex.
[ihejddjcdmdppiimegmknbcaiebklajl-1552051913938.log](https://github.com/Glagan/MyMangaDex/files/2945986/ihejddjcdmdppiimegmknbcaiebklajl-1552051913938.log)
Here's the console log in chrome. Not sure if it helps.

**Comment by Glagan** [comment]
Thanks for the issue, I think it's fixed, the update need to be published and you will be able to update.

**Comment by ringosham** [comment]
Just tried the new version (2.0.6)
mangadex.org/title/undefined:1 Failed to load resource: the server responded with a status of 404 ()
optionsManager.js:1 TypeError: Cannot read property 'textContent' of null
    at OptionsManager.updateLocalFromMDMAL (optionsManager.js:1)

this.mangaDexMangaList[a] in line 401 of updateLocalFromMDMAL is undefined.

**Comment by ringosham** [comment]
My guess is because my list is empty right now.

**Comment by Glagan** [comment]
Ho, maybe, but if your MangaDex follow list is empty the import will do nothing, all it does is updating MyMangaDex storage to have the last chapter set as the chapter on MyAnimeList for every manga in your MangaDex follow list, it doesn't retrieve titles on MangaDex and set them as "reading" or anything else.

I will look at it again tomorrow to fix when the list is empty, and maybe add a better description of what it does.

**Comment by ringosham** [comment]
Oh, I see. I thought it automatically adds entries.

**Comment by Glagan** [comment]
Thanks for helping me resolve this issue, I updated the extension to fix the problem and I also updated the message, which was misleading now that I read it.

**Comment by ringosham** [comment]
You're welcome. :D
