### ISSUE TITLE
Not working on FireFox for Android anymore

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#63]
Title says it.
Either correct the ReadMe or update the extension (if even possible) https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/

**Comment by Glagan** [comment]
The extension works perfectly on Android, it's just the new firefox that is broken.
I ran ``web-ext lint`` as explained in your link with no errors, and the extension also had a really low ``min_strict_version`` for a long time.

The only way to fix this is to wait, the latest Firefox version is sadly still a beta pushed wrongly to release, I personally don't like it and don't really feel the performance improvements, I still have the old version not updated and use Firefox Nightly to test the new one.
If you kept the old version you could still use MyMangaDex.

As an alternative you can use Tachiyomi with MyAnimeList sync, but you'll run into the same problems some other users had with syncing without going to a Title Page.
