### ISSUE TITLE
[Feature Suggestion] Removing from list.

### ISSUE THREAD

**Issue by dunia01** [Glagan/MyMangaDex#64]
I didn't found a way to properly remove a manga from MD and MAL at the same time with this extension so now I'm suggesting it. Sometimes people only want to peek at some stories a.k.a. the first chapter and if disliked, don't even add it to the list.

**Comment by cpiber** [comment]
You can go to "Edit on MyAnimeList" (button on the title page or the right-most of the four (orig. three) in the reader), then select "Delete on MyAnimeList"
As far as I know there is no option to remove it from localstorage if the title isn't on MAL.

**Comment by dunia01** [comment]
> As far as I know there is no option to remove it from localstorage if the title isn't on MAL.
That's a situation I've stumbled into.

> You can also turn on that only titles in your Reading List are updated, then it optionally asks you whether you still want to add and update
I have this Global Setting on and It doesn't help, the manga still appear at the Follow and History page.

**Comment by cpiber** [comment]
Are you sure that you have "Update only if in MangaDex list" on? For me it always asks... It's possible you also need "Confirm to update chapter", though I doubt that

**Comment by dunia01** [comment]
Yep. The one manga that I'm having this problem is coincidentally one that don't have a MAL page: Honkai Impact 3rd.

I may have that option off when I tried to read a chapter, and after I customized the extension at my liking I don't think I can reverse that.

**Comment by cpiber** [comment]
A somewhat tricky solution would be to export your settings (which includes all data). You will get a file in JSON format. You could try to find the title in it (the keys are the MD title ids) and remove the whole object, then save and import again.

The portion you'll need to remove is `"22297":{"mal":0,"last":-1,"chapters":[]},` (where "mal" and "last" could be any number there probably is more between the `[]` for "chapters". Take care to remove exactly that or you might get an error when importing. Make a backup. The title id I used here is of https://mangadex.org/title/22297/honkai-impact-3rd, I believe this should be the one you mentioned.

I think a mock of the "Edit" dialog could be a good idea.

**Comment by dunia01** [comment]
I'll try that, thank you for your support. Certainly It is an unique situation that I've got into.

**Comment by dunia01** [comment]
Following your guide I removed that section but while trying to import, removing only that section caused a error. I've found a `"history:[]"` section that all title IDs were and removing 22297 there I can finally import without errors, but did not work even after pressing save, making sure both import and save gets a green flash.

**Comment by cpiber** [comment]
The "history" property isn't used to determine whether you follow a title. Did you make sure to also remove the "," after the "}"? If you'd like you can also send me your save file and I can remove it for you.

**Comment by dunia01** [comment]
Yeah I did remember to delete that comma. Sure.

**Comment by dunia01** [comment]
After a couple of messages I've followed this route:
- Exported my save file. 
- Deleted all MyMangaDex extension data.
- Saved.
- Closed my internet browser (chrome) entirely. Reopened.
- Imported my save file without the manga section and its title ID in the history section.
- Saved.

The result is that the manga stoped showing up in the Follows page but still shows up in the History page, also exporting a new save file I can see that somehow the manga section and he title ID reappeared. Doing all that a second or third time does nothing.

**Comment by Glagan** [comment]
What  do you mean exactly by ``the manga still appear at the Follow and History page.`` ?
A Title being in your Follow page is not related to MyMangaDex, you need to remove it from your MangaDex follow list.  
For the History, if the Title is one the last 10 you read, then it's also in your MangaDex history and it will just disappear once you read more titles.

There is no save editor in MyMangaDex sadly, but if you want to remove a title the Delete button should delete it on MyAnimeList but it will stay in your MyMangaDex save.

**Comment by dunia01** [comment]
> What do you mean exactly by `the manga still appear at the Follow and History page.` ?

I understand now. I was wrongly believing, because of MMD's History size change in the History page, that this system configuration overlapped whatever It was my History page normally, thinking that If I removed, unfollowed or dismantled the connection to MAL, the manga title would disappear from the History page too.

Tha manga title I wanted to totally remove from my MMD integration, because I just peeked some chapters, stopped appearing at my Follows page already after I followed that step-by-step.

The thing is that when a manga title isn't on MAL and I want to remove it from my account (don't selecting any option from the follow action in the MangaDex) after reading a chapter, the manga title will appear at the Follows page as somehow I'm following it and have colored highlights in the chapters I interacted with at its manga page. At least this is what was happening to me. Sorry for the trouble.

**Comment by Glagan** [comment]
From what I understand you just need to **Unfollow** the title (not related to MyMangaDex), and everything should be fine.  
![image](https://user-images.githubusercontent.com/8447621/98824652-d88d4100-2433-11eb-8a05-da8761a434cc.png)

**Comment by dunia01** [comment]
Strange, because I never followed that manga title to begin with, that's what I'm trying to say.

**Comment by Glagan** [comment]
If you have the **Update MangaDex list** options enabled (in the **Global** section) it automatically set it to **Reading** when you open a chapter.  
I don't remember any other way that MyMangaDex automatically adds a title to your MangaDex list, so either you had this option enabled or you forgot you added it.

**Comment by dunia01** [comment]
I didn't had that option on while reading it, I customized MMD's settings after. Well, as cpiber [mentioned](https://github.com/Glagan/MyMangaDex/issues/64#issuecomment-724909024), that could replace my suggestion in the matter.
