### ISSUE TITLE
Avoid volume reset v2

### ISSUE THREAD

**Issue by Myorave** [Glagan/MyMangaDex#67]
Hi again, i've opened a thread yesterday in which I enquired to you about the fact that when we're reading a chapter that do not have a volume number in it's chapter title, MyMangaDex wll reset the volume number to 0. I saw that you made a commit 2h after I started my request and I thank you for your work.

The problem is that this fix **do not solve this problem**, at least on my end. I uninstalled/reinstalled MyMangaDex, I updated the extension which currenly shows that I have the version 2.4.18,
![image](https://user-images.githubusercontent.com/26874352/101801881-1ce12f00-3b0f-11eb-8f08-3fb88d769480.png)
 I tried to download this through Chrome Store and even tried to download the package from Github to the local extension folder of my navigator but the problem still persists.

**Here are the screenshots I put in hte previous thread to illustrate this issue:**
Before reading chapter 59:
![image](https://user-images.githubusercontent.com/26874352/101800838-01c1ef80-3b0e-11eb-94fe-b84781f974bc.png)

After reading chapter 59:
![image](https://user-images.githubusercontent.com/26874352/101800857-08e8fd80-3b0e-11eb-8484-c85dddaf931a.png)

Here is a screenshot to show the kind of chapter name this can trigger this issue:
![image](https://user-images.githubusercontent.com/26874352/101800877-0e464800-3b0e-11eb-8f3e-3b9dbf621a57.png)

These one doesn't trigger this issue:
![image](https://user-images.githubusercontent.com/26874352/101800890-12726580-3b0e-11eb-91e3-4ea7d8ac471e.png)

**Comment by Glagan** [comment]
Hum, sorry I should have asked if it was working on your end before closing the issue.  
That's weird, could you link the manga it's not working for ? It works for me, on [Mieruko-cha](https://mangadex.org/title/31792/mieruko-chan) for example, reading anything with a volume and reading the last chapter keep the volume 2, and I tested on both Firefox and Chrome, and I don't see any option that would make it not works.

Did you actually *updated* a title when testing on the latest version (2.4.18), and by that I mean you saw a Confirmation notification, if you have the ``updateOnlyHigher`` or ``updateOnlyNext`` options enabled for example.

**Comment by Myorave** [comment]
Hi again, I tried to reproduce the same issue with Mieruko-chan and it does the same issue on my end. 
I tried in both Brave (which is a Chromium browser) and Chrome and it occured in both cases.

**Before reading chapter 29 of Mieruko-chan:**
![image](https://user-images.githubusercontent.com/26874352/101805317-e7d6db80-3b12-11eb-8457-9c1435296c88.png)
![image](https://user-images.githubusercontent.com/26874352/101805334-edccbc80-3b12-11eb-8230-879be3981cbb.png)

**After reading chapter 29:**
![image](https://user-images.githubusercontent.com/26874352/101805420-06d56d80-3b13-11eb-95e2-845572956ac3.png)
![image](https://user-images.githubusercontent.com/26874352/101805439-0b9a2180-3b13-11eb-91b2-dc50f85ecb0a.png)

Here are my settings for the chapter page section:
![image](https://user-images.githubusercontent.com/26874352/101805723-603d9c80-3b13-11eb-8e3c-244318462d55.png)
I can send you a dump of my settings if it can help you

For exemple, [Reincarnated as an Aristocrat with an Appraisal Skill](https://mangadex.org/title/51376/reincarnated-as-an-aristocrat-with-an-appraisal-skill) which does not have volume number in its chapter names trigger this problem.

**Comment by Myorave** [comment]
When reading an unread chapter whose number is higher than the one on my MAL, this notification pops up on the bottom left:
![image](https://user-images.githubusercontent.com/26874352/101807653-a3007400-3b15-11eb-8acd-f57785abe0f3.png)

**Comment by Myorave** [comment]
Also to mention, this problem also occurs when clicking the eye button next to the chapter name (even if it has a volume number in it).

**Comment by Glagan** [comment]
Actually forgot the volume wasn't stored in the save and only fetched from **MyAnimeList**, the last commit should fix the issue, I'll let it open just in case.  
It should be up for Firefox but I don't know when for Chrome.

**Comment by Myorave** [comment]
**Thanks a lot! It works like a charm!**
There is just **one issue** that could be awesome if it could be fixed (but I could understand if it's not a priority). It is still about **preventing the volume reset** but now, it is about clicking the eye button (the proof of reading) next to the chapter (whether it's on the follow or the manga page).

For exemple, if I've read a chapter on another website (for instance a Raw) and when I come back to MangaDex, I see the same chapter on my follow feed, I will click on the eye button to remind me that i've already read this chapter (and also automaticaly update it to MAL). The problem is like before, the chapter number is correctly updated but not the volume number, with a little difference on this case which is that the volume number will reset even if there is a volume number on the chapter name.

But again, thanks for correcting the previous issue!

**Comment by Glagan** [comment]
Volume should be correctly updated when using the eye icon to set **as read**, but the opposite will still reset the volume (maybe to 0), since there is no previous volume saved and I won't add it to MyMangaDex since it means I would have to add the field on all pages where it's available, on the Online Save, check for Import/Export... and I don't want to, since the next version is probably coming next week and it shouldn't have this problem.

**Comment by Myorave** [comment]
Understood, thanks a lot for your time and for solving this issue!
Have a nice day!
