### ISSUE TITLE
New year (2021) not available in start & finish dates

### ISSUE THREAD

**Issue by Myorave** [Glagan/MyMangaDex#69]
Hi, well first I wish you a happy new year 🥳🎉 
I would like to inquire about a problem concerning the start & finish dates of a manga. 
Today is the start of a new year but the year "2021" is not available in the year dropdown as you can see in the screenshot below.
![image](https://user-images.githubusercontent.com/26874352/103444139-f9b92380-4c65-11eb-914f-148ecac14853.png)

**Comment by Glagan** [comment]
Sorry about that, should be fixed in the next update, and happy new year :)
