### ISSUE TITLE
 Mangadex Api v2 Support

### ISSUE THREAD

**Issue by Myorave** [Glagan/MyMangaDex#71]
Hi, I would like to inquire about a problem that came up since a few hours which is the fact that MangaDex updated their API and thus, broke the behaviour of MyMangaDex.

I saw that this problem was corrected for SyncDex. Could it be possible to also correct this for MMD ?

**Comment by Glagan** [comment]
I'll work on that, shouldn't be hard I did it once already :)

**Comment by Glagan** [comment]
Fixed in version ``2.4.23`` that should be up on all platforms.
