### ISSUE TITLE
Any chance of AniList support sometime in the future?

### ISSUE THREAD

**Issue by noahgaertner** [Glagan/MyMangaDex#72]

**Comment by cpiber** [comment]
MyMangaDex is only for MyAnimeList. If you want other services, check out the successor [SyncDex](https://github.com/Glagan/SyncDex).

**Comment by Glagan** [comment]
Like @cpiber said, if you want to sync to **Anilist**, you can install [SyncDex](https://github.com/Glagan/SyncDex), which is still in beta, but relatively stable, has the same (and more) features as **MyMangaDex** and support for Anilist, Kitsu, AnimePlanet and MangaUpdates on top of MyAnimeList :)

If you already were using MyMangaDex for some time and don't want to lose your save, you can Import it in SyncDex, but it's recommend to just make sur your MyAnimeList is up to date and import MyAnimeList directly.

I don't plan to update MyMangaDex to add more features, and I will only be working on **SyncDex**, altough I will still try to fix any reported bugs for MyMangaDex, and update for the MangaDex updates if it's not too much work.

**Comment by noahgaertner** [comment]
Thanks for the info! Will do that instead.
