### ISSUE TITLE
Can't register for online save

### ISSUE THREAD

**Issue by DerpyDino77** [Glagan/MyMangaDex#73]
Hi, I just tried to register for the online save feature, but whenever I click register it just flashes red. I've tried logging in, changing username/password yet nothing seems to work. I'm currently using Edge as my browser so that might have something to do with it, but seeing as it's a chromium browser it don't feel like that is the problem (also tried on my laptop as well and had the same issue).
Thanks in advance

**This is how it looks afterwards**
![image](https://user-images.githubusercontent.com/78676182/107138441-60112000-694f-11eb-8868-bfe0f53b95e9.png)

**Comment by Glagan** [comment]
Hi, I can see the error in the logs, it's on the server side, looks like there is a weird error with dependencies since all tests pass and it's working in local, I'm re-uploading the dependencies and it should be good, I'll post an update once it's working again.

**Comment by Glagan** [comment]
It should be working now !

**Comment by DerpyDino77** [comment]
Just checked and it works now :)
Appreciate the fast response and all the good work you've been doing.
