### ISSUE TITLE
Unable to disable highlights

### ISSUE THREAD

**Issue by blue-lightning** [Glagan/MyMangaDex#9]
I want to opt out of the last read chapter highlight, but the option's not working. Screenshots here: https://imgur.com/a/nuzCYfU

**Comment by Glagan** [comment]
I'll look at it, you can set the colors you don't want to ``transparent`` in the meanwhile.

**Comment by Glagan** [comment]
@blue-lightning It's working for me, are you sure you pressed the **Save** button.
If that's it I will change it's behaviour it's only a source of trouble, even for me.

**Comment by blue-lightning** [comment]
Already saved, I've even closed Firefox and then restart; the option changed but highlights were still there. That said, since lots of folks seems to like this feature I don't think you should change much if possible. How about just remove the "Highlight chapters" switch and add a note about `transparent` value under the Color section?

**Comment by Glagan** [comment]
Can you still send me your save (via private message if you want) so I'll see if there is something wrong with it or if it's somewhere else.

**Comment by blue-lightning** [comment]
No problem, here:

`{"80":{"mal":18939,"last":37,"chapters":[37,31]},"4534":{"mal":10443,"last":101,"chapters":[101,0]},"7139":{"mal":44347,"last":110,"chapters":[110,109,108,107,106,0]},"10642":{"mal":63579,"last":39,"chapters":[39]},"11453":{"mal":69423,"last":0,"chapters":[]},"13124":{"mal":72113,"last":13,"chapters":[13]},"15329":{"mal":88660,"last":1,"chapters":[1]},"15940":{"mal":91663,"last":7,"chapters":[7]},"26270":{"mal":0,"last":1,"chapters":[1]},"35129":{"mal":0,"last":37,"chapters":[37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]},"38115":{"mal":0,"last":108,"chapters":[108]},"options":{"lastReadColor":"transparent","lowerChaptersColor":"transparent","lastOpenColors":["transparent"],"openedChaptersColor":"transparent","hideLowerChapters":false,"saveOnlyHigher":true,"saveAllOpened":true,"maxChapterSaved":"100","updateHistoryPage":false,"historySize":"100","updateMDList":true,"showTooltips":false,"highlightChapters":false,"showNotifications":false,"showErrors":false,"showNoMal":false,"onlineSave":false,"onlineURL":"https://mmd.nikurasu.org/api/","username":"","isLoggedIn":false,"token":"","version":2.1,"subVersion":2}}`

**Comment by Glagan** [comment]
I actually forgot to check if the option was enabled in one function, it's fixed, thanks :)
